### ISSUE TITLE
ExecuteProcedure shortcut method

### ISSUE THREAD

**Issue by 854R** [yajra/laravel-oci8#321]
### Summary of problem or feature request

Anyone using the shortcut method successfully? I'm getting a "wrong number of arguments" error when I call a stored procedure that takes 2 IN parameters and inserts a new record in a table.

When I dump the exception error, it shows that the stored procedure is being called with 3 parameters - the 3rd being :cursor. I don't have a 3rd parameter in my stored procedure. The ExecuteProcedure seems to be inserting it.

When I use the manual method (as per the Yajra docs), it works fine since there is no 3rd parameter being coded. I'd like to use the shortcut method as it's more compact to code.

Thanks.

### Code snippet of problem

```php
$bindings = [ $user['emplid'], $user['pno'] ];
$result = DB::executeProcedure('MyPackage.InsertProfile', $bindings);
```

### System details

- Operating System
- PHP Version: 7.0.21
- Laravel Version: 5.4
- Laravel-OCI8 Version: 5.4?

**Comment by yajra** [comment]
@mstaack is currently refactoring this method. Maybe you could provide some inputs / help testing his PR https://github.com/yajra/laravel-oci8/pull/319?

**Comment by mstaack** [comment]
@854R @yajra  this should be fixed with mit pr  then you just use executeProcedure

**Comment by 854R** [comment]
Hi, please advise what the release number of this fix is. I just updated to version 5.4.13 a while ago and I'm still getting the same error i.e. wrong number of arguments.

Thanks.

**Comment by mstaack** [comment]
@854R sorry this is has not been merged yet... have a look here for updates https://github.com/yajra/laravel-oci8/pull/319
